<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEditionBasic\Service\ConfigurationService' shared service.

return $this->services['PrestaShop\\Module\\PsEditionBasic\\Service\\ConfigurationService'] = new \PrestaShop\Module\PsEditionBasic\Service\ConfigurationService();
