<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\Mbo\Handler\ErrorHandler\ErrorHandler' shared service.

return $this->services['PrestaShop\\Module\\Mbo\\Handler\\ErrorHandler\\ErrorHandler'] = new \PrestaShop\Module\Mbo\Handler\ErrorHandler\ErrorHandler();
