<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.cdc.context_builder' shared service.

return $this->services['mbo.cdc.context_builder'] = new \PrestaShop\Module\Mbo\Service\View\ContextBuilder(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['prestashop.core.admin.module.repository'] ?? $this->getPrestashop_Core_Admin_Module_RepositoryService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['doctrine.cache.provider'] ?? $this->getDoctrine_Cache_ProviderService()), ($this->services['mbo.security.admin_authentication.provider'] ?? $this->getMbo_Security_AdminAuthentication_ProviderService()), ($this->services['mbo.accounts.data_provider'] ?? ($this->services['mbo.accounts.data_provider'] = new \PrestaShop\Module\Mbo\Accounts\Provider\AccountsDataProvider('5.2.5'))));
