<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.distribution.config_applier' shared service.

return $this->services['mbo.distribution.config_applier'] = new \PrestaShop\Module\Mbo\Distribution\Config\Applier(($this->services['mbo.distribution.config_appliers_factory'] ?? $this->load('getMbo_Distribution_ConfigAppliersFactoryService.php')));
