<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.api.service.executors.module_transition' shared service.

return $this->services['mbo.api.service.executors.module_transition'] = new \PrestaShop\Module\Mbo\Api\Service\ModuleTransitionExecutor(($this->services['mbo.modules.state_machine.module_status_transition_handler'] ?? $this->load('getMbo_Modules_StateMachine_ModuleStatusTransitionHandlerService.php')));
