<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.collection.factory' shared service.

return $this->services['mbo.modules.collection.factory'] = new \PrestaShop\Module\Mbo\Module\CollectionFactory();
