<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.event_subscriber' shared service.

return $this->services['mbo.addons.event_subscriber'] = new \PrestaShop\Module\Mbo\Addons\Subscriber\ModuleManagementEventSubscriber(($this->services['logger'] ?? $this->getLoggerService()), ($this->services['mbo.modules.repository'] ?? $this->load('getMbo_Modules_RepositoryService.php')), ($this->services['mbo.tab.collection.provider'] ?? $this->load('getMbo_Tab_Collection_ProviderService.php')), ($this->services['mbo.cdc.context_builder'] ?? $this->load('getMbo_Cdc_ContextBuilderService.php')), ($this->services['mbo.cdc.client.distribution_api'] ?? $this->load('getMbo_Cdc_Client_DistributionApiService.php')), ($this->services['mbo.security.admin_authentication.provider'] ?? $this->getMbo_Security_AdminAuthentication_ProviderService()), ($this->services['mbo.distribution.api_version_change_config_apply_handler'] ?? $this->load('getMbo_Distribution_ApiVersionChangeConfigApplyHandlerService.php')), ($this->services['mbo.symfony_cache_clearer'] ?? ($this->services['mbo.symfony_cache_clearer'] = new \PrestaShop\Module\Mbo\Service\MboSymfonyCacheClearer())));
