<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.tab.collection.factory' shared service.

return $this->services['mbo.tab.collection.factory'] = new \PrestaShop\Module\Mbo\Tab\TabCollectionFactory(($this->services['mbo.modules.repository'] ?? $this->load('getMbo_Modules_RepositoryService.php')));
