<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.presenter.shopData' shared service.

return $this->services['ps_metrics.presenter.shopData'] = new \PrestaShop\Module\Ps_metrics\Presenter\ShopDataPresenter(($this->services['ps_metrics.module'] ?? $this->load('getPsMetrics_ModuleService.php')), ($this->services['ps_metrics.helper.prestashop'] ?? ($this->services['ps_metrics.helper.prestashop'] = new \PrestaShop\Module\Ps_metrics\Helper\PrestaShopHelper())), ($this->services['ps_metrics.repository.configuration'] ?? $this->load('getPsMetrics_Repository_ConfigurationService.php')), ($this->services['ps_metrics.helper.shop'] ?? $this->load('getPsMetrics_Helper_ShopService.php')), ($this->services['ps_metrics.provider.analyticsaccountslist'] ?? $this->load('getPsMetrics_Provider_AnalyticsaccountslistService.php')), ($this->services['ps_metrics.module.gainstaller'] ?? $this->load('getPsMetrics_Module_GainstallerService.php')), ($this->services['ps_accounts.facade'] ?? $this->load('getPsAccounts_FacadeService.php')), ($this->services['ps_metrics.helper.tools'] ?? ($this->services['ps_metrics.helper.tools'] = new \PrestaShop\Module\Ps_metrics\Helper\ToolsHelper())), ($this->services['ps_metrics.helper.multishop'] ?? ($this->services['ps_metrics.helper.multishop'] = new \PrestaShop\Module\Ps_metrics\Helper\MultishopHelper())));
