<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.api.analytics' shared service.

return $this->services['ps_metrics.api.analytics'] = new \PrestaShop\Module\Ps_metrics\Api\AnalyticsApi(($this->services['ps_metrics.api.client.analytics'] ?? $this->load('getPsMetrics_Api_Client_AnalyticsService.php')), ($this->services['ps_metrics.helper.config'] ?? $this->load('getPsMetrics_Helper_ConfigService.php')));
