<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.legacy.installer' shared service.

return $this->services['ps_metrics.legacy.installer'] = new \PrestaShop\Module\Ps_metrics\LegacyModuleInstaller(($this->services['ps_metrics.module'] ?? $this->load('getPsMetrics_ModuleService.php')));
