<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQG1nwnG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQG1nwnG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQG1nwnG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQG1nwnG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQG1nwnG\appAppKernelProdContainer([
    'container.build_hash' => 'QG1nwnG',
    'container.build_id' => '3153e65a',
    'container.build_time' => 1706353044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQG1nwnG');
