<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCanhavx\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCanhavx/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerCanhavx.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerCanhavx\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerCanhavx\appAppKernelProdContainer([
    'container.build_hash' => 'Canhavx',
    'container.build_id' => 'a15b26b7',
    'container.build_time' => 1706355735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCanhavx');
