<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.identifier.uuid_normalizer' shared service.

@trigger_error('The "api_platform.identifier.uuid_normalizer" service is deprecated since 2.7 and will be removed in 3.0. Use the "api_platform.ramsey_uuid.uri_variables.transformer.uuid" service instead.', E_USER_DEPRECATED);

return $this->privates['api_platform.identifier.uuid_normalizer'] = new \ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer();
