<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxMarketingWithGoogle\Repository\CountryRepository' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\CountryRepository'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Repository\CountryRepository(($this->services['psxmarketingwithgoogle.db'] ?? $this->load('getPsxmarketingwithgoogle_DbService.php')), ($this->services['psxmarketingwithgoogle.context'] ?? $this->load('getPsxmarketingwithgoogle_ContextService.php')), ($this->services['psxmarketingwithgoogle.country'] ?? $this->load('getPsxmarketingwithgoogle_CountryService.php')), ($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Adapter\\ConfigurationAdapter'] ?? $this->load('getConfigurationAdapter2Service.php')));
