<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\Mbo\Api\Config\Env' shared service.

return $this->services['PrestaShop\\Module\\Mbo\\Api\\Config\\Env'] = new \PrestaShop\Module\Mbo\Api\Config\Env();
