<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.prestashop_components.context' shared service.

return $this->services['klaviyops.prestashop_components.context'] = \Context::getContext();
