<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.externalcontent.provider' shared service.

return $this->services['mbo.externalcontent.provider'] = new \PrestaShop\Module\Mbo\Service\ExternalContentProvider\ExternalContentProvider();
