<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.builder' shared service.

return $this->services['mbo.modules.builder'] = new \PrestaShop\Module\Mbo\Module\ModuleBuilder(($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')), ($this->services['logger'] ?? $this->getLoggerService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("_PS_MODULE_DIR_"));
