<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\Mbo\Api\Repository\ModuleRepository' shared service.

return $this->services['PrestaShop\\Module\\Mbo\\Api\\Repository\\ModuleRepository'] = new \PrestaShop\Module\Mbo\Api\Repository\ModuleRepository();
