<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.api.service.executors.config_apply' shared service.

return $this->services['mbo.api.service.executors.config_apply'] = new \PrestaShop\Module\Mbo\Api\Service\ConfigApplyExecutor(($this->services['mbo.distribution.api_config_change_handler'] ?? $this->load('getMbo_Distribution_ApiConfigChangeHandlerService.php')), ($this->services['ps_mbo'] ?? $this->load('getPsMboService.php')));
