<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.state_machine.module_status_transition_handler' shared service.

return $this->services['mbo.modules.state_machine.module_status_transition_handler'] = new \PrestaShop\Module\Mbo\Module\CommandHandler\ModuleStatusTransitionCommandHandler(($this->services['mbo.modules.state_machine'] ?? $this->load('getMbo_Modules_StateMachineService.php')), ($this->services['mbo.modules.repository'] ?? $this->load('getMbo_Modules_RepositoryService.php')), ($this->services['mbo.modules.actions_manager'] ?? $this->load('getMbo_Modules_ActionsManagerService.php')), ($this->services['mbo.modules.builder'] ?? $this->load('getMbo_Modules_BuilderService.php')));
