<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.user' shared service.

return $this->services['mbo.addons.user'] = new \PrestaShop\Module\Mbo\Addons\User\AddonsUser(($this->services['session'] ?? $this->getSessionService()), ($this->services['mbo.addons.user.credentials_encryptor'] ?? $this->getMbo_Addons_User_CredentialsEncryptorService()), ($this->services['mbo.accounts.data_provider'] ?? ($this->services['mbo.accounts.data_provider'] = new \PrestaShop\Module\Mbo\Accounts\Provider\AccountsDataProvider('5.2.5'))));
