<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.tab.collection.provider' shared service.

return $this->services['mbo.tab.collection.provider'] = new \PrestaShop\Module\Mbo\Tab\TabCollectionProvider(($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['mbo.externalcontent.provider'] ?? ($this->services['mbo.externalcontent.provider'] = new \PrestaShop\Module\Mbo\Service\ExternalContentProvider\ExternalContentProvider())), ($this->services['mbo.tab.collection.factory'] ?? $this->load('getMbo_Tab_Collection_FactoryService.php')), ($this->services['doctrine.cache.provider'] ?? $this->getDoctrine_Cache_ProviderService()));
