<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.state_machine' shared service.

return $this->services['mbo.modules.state_machine'] = new \PrestaShop\Module\Mbo\Module\Workflow\ModuleStateMachine(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['translator'] ?? $this->getTranslatorService()));
