<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8JK44g\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8JK44g/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerX8JK44g.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerX8JK44g\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerX8JK44g\appAppKernelProdContainer([
    'container.build_hash' => 'X8JK44g',
    'container.build_id' => '459f033d',
    'container.build_time' => 1706355685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8JK44g');
