<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.toolbar' shared service.

return $this->services['mbo.addons.toolbar'] = new \PrestaShop\Module\Mbo\Addons\Toolbar(($this->services['mbo.security.permission_checker'] ?? $this->load('getMbo_Security_PermissionCheckerService.php')), ($this->services['mbo.addons.data_provider'] ?? $this->load('getMbo_Addons_DataProviderService.php')), ($this->services['translator'] ?? $this->getTranslatorService()));
