<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.data_provider' shared service.

$this->services['mbo.addons.data_provider'] = $instance = new \PrestaShop\Module\Mbo\Addons\Provider\AddonsDataProvider(($this->services['mbo.addons.client.api'] ?? $this->load('getMbo_Addons_Client_ApiService.php')), ($this->services['mbo.addons.user.provider'] ?? $this->load('getMbo_Addons_User_ProviderService.php'))->getUser(), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()))->get("ADDONS_API_MODULE_CHANNEL", "stable"));

$instance->cacheDir = $this->targetDir.'';

return $instance;
