<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.actions_manager' shared service.

return $this->services['mbo.modules.actions_manager'] = new \PrestaShop\Module\Mbo\Module\ActionsManager(($this->services['mbo.modules.files_manager'] ?? $this->load('getMbo_Modules_FilesManagerService.php')), ($this->services['mbo.modules.repository'] ?? $this->load('getMbo_Modules_RepositoryService.php')));
