<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.links_provider' shared service.

return $this->services['mbo.addons.links_provider'] = new \PrestaShop\Module\Mbo\Addons\Provider\LinksProvider(($this->services['prestashop.core.foundation.version'] ?? $this->load('getPrestashop_Core_Foundation_VersionService.php')), ($this->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? $this->getLegacyContextService()), ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['prestashop.categories_provider'] ?? $this->getPrestashop_CategoriesProviderService()), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['prestashop.router'] ?? $this->load('getPrestashop_RouterService.php')));
