<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.accounts.data_provider' shared service.

return $this->services['mbo.accounts.data_provider'] = new \PrestaShop\Module\Mbo\Accounts\Provider\AccountsDataProvider('5.2.5');
