<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.distribution.config_appliers_factory' shared service.

return $this->services['mbo.distribution.config_appliers_factory'] = new \PrestaShop\Module\Mbo\Distribution\Config\Appliers\Factory([0 => ($this->services['mbo.distribution.theme_catalog_menu_config_applier'] ?? ($this->services['mbo.distribution.theme_catalog_menu_config_applier'] = new \PrestaShop\Module\Mbo\Distribution\Config\Appliers\ThemeCatalogMenuConfigApplier())), 1 => ($this->services['mbo.distribution.module_selection_menu_config_applier'] ?? ($this->services['mbo.distribution.module_selection_menu_config_applier'] = new \PrestaShop\Module\Mbo\Distribution\Config\Appliers\ModuleSelectionMenuConfigApplier()))]);
