<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.modules.state_machine.eventsubscriber.transition' shared service.

return $this->services['mbo.modules.state_machine.eventsubscriber.transition'] = new \PrestaShop\Module\Mbo\Module\Workflow\Event\TransitionEventSubscriber(($this->services['mbo.modules.state_machine.transitions_manager'] ?? $this->load('getMbo_Modules_StateMachine_TransitionsManagerService.php')));
