<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_edition_basic.presenter.setupGuideData' shared service.

return $this->services['ps_edition_basic.presenter.setupGuideData'] = new \PrestaShop\Module\PsEditionBasic\Presenter\SetupGuideDataPresenter(($this->services['ps_edition_basic.module'] ?? $this->load('getPsEditionBasic_ModuleService.php'))->getTranslator());
