<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.module.gainstaller' shared service.

return $this->services['ps_metrics.module.gainstaller'] = new \PrestaShop\Module\Ps_metrics\Module\GAInstaller(($this->services['ps_metrics.module'] ?? $this->load('getPsMetrics_ModuleService.php')), ($this->services['ps_metrics.helper.module'] ?? $this->load('getPsMetrics_Helper_ModuleService.php')), ($this->services['ps_metrics.helper.tools'] ?? ($this->services['ps_metrics.helper.tools'] = new \PrestaShop\Module\Ps_metrics\Helper\ToolsHelper())), ($this->services['ps_metrics.helper.prestashop'] ?? ($this->services['ps_metrics.helper.prestashop'] = new \PrestaShop\Module\Ps_metrics\Helper\PrestaShopHelper())));
