<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.module.uninstall' shared service.

return $this->services['ps_metrics.module.uninstall'] = new \PrestaShop\Module\Ps_metrics\Module\Uninstall(($this->services['ps_accounts.facade'] ?? $this->load('getPsAccounts_FacadeService.php')), ($this->services['ps_metrics.repository.configuration'] ?? $this->load('getPsMetrics_Repository_ConfigurationService.php')), ($this->services['ps_metrics.api.analytics'] ?? $this->load('getPsMetrics_Api_AnalyticsService.php')));
