<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.statstab.manager' shared service.

return $this->services['ps_metrics.statstab.manager'] = new \PrestaShop\Module\Ps_metrics\StatsTabManager(($this->services['ps_metrics.module'] ?? $this->load('getPsMetrics_ModuleService.php')), ($this->services['ps_accounts.facade'] ?? $this->load('getPsAccounts_FacadeService.php')));
